name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # ✅ Updated to v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # ✅ Updated to v4
        with:
          node-version: "20" # ✅ Use latest stable version
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3 # ✅ Ensure correct version
        with:
          name: build-files
          path: dist/ # Update based on your build output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3 # ✅ Correct artifact retrieval
        with:
          name: build-files
          path: dist/

      - name: Deploy Application
        run: echo "Deploying application..."
