name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # ✅ Use Windows instead of Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4  # ✅ Latest version
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3  # ✅ Upload built files
        with:
          name: build-files
          path: dist/  # ✅ Make sure this path exists

  deploy:
    runs-on: windows-latest  # ✅ Use Windows instead of Ubuntu
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3  # ✅ Latest version
        with:
          name: build-files
          path: dist/

      - name: Deploy Application
        run: echo "Deploying application..."
