name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # You can use windows-latest if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Use the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4  # ✅ Use the latest version
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3  # ✅ Ensure correct version
        with:
          name: build-files
          path: dist/  # Adjust based on your project
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3  # ✅ Ensure correct version
        with:
          name: build-files
          path: dist/

      - name: Deploy Application
        run: echo "Deploying application..."
